### ISSUE TITLE
Modify the value of the PERCENTAGE parameter

### ISSUE THREAD

**Issue by fxfyio** [sophon-org/sophon-light-node#13]
I have successfully run the node using Docker, and now I want to modify the value of the PERCENTAGE parameter. What way can I modify it?

**Comment by ashwaq06** [comment]
Stop you Container and run a container with new Percentage Value
`docker stop sophon-light-node`
`docker rm sophon-light-node`

```
docker run -d --name sophon-light-node \
    -e OPERATOR_ADDRESS=<Your operator wallet address> \
    -e DESTINATION_ADDRESS=<The rewards destination wallet address> \
    -e PERCENTAGE=<New Percentage Value> \
    -e PUBLIC_DOMAIN=<Your public URL/IP> \
    -e PORT=<Service Port> \
    -p <External Port>:<Internal Port> \
    sophonhub/sophon-light-node
```
---
Or else you can use docker compose for this
```
version: "3.8"
services:
  sophon-light-node:
    image: sophonhub/sophon-light-node
    environment:
      - OPERATOR_ADDRESS=<Your operator wallet address>
      - DESTINATION_ADDRESS=<The rewards destination wallet address>
      - PERCENTAGE=<New Percentage Value>
      - PUBLIC_DOMAIN=<Your public URL/IP>
      - PORT=<Service Port>
    ports:
      - "<External Port>:<Internal Port>"
```
 
Then, apply the changes:

`docker-compose up -d`
